/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarContent: typeof import('./src/components/dashboard/BarContent.vue')['default']
    DashboardCard: typeof import('./src/components/dashboard/DashboardCard.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    LineContent: typeof import('./src/components/dashboard/LineContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValueCard: typeof import('./src/components/ValueCard.vue')['default']
    ValueContent: typeof import('./src/components/dashboard/ValueContent.vue')['default']
  }
}
