/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    PixiGauge: typeof import('./src/components/PixiGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValueCard: typeof import('./src/components/ValueCard.vue')['default']
  }
}
